# Main Nginx configuration file

events {
    worker_connections 1024;  # Maximum number of simultaneous connections
}

http {
    include       mime.types;  # Include MIME types
    default_type  application/octet-stream;

    sendfile        on;  # Enable efficient file transfers
    keepalive_timeout  65;  # Timeout for keep-alive connections

    server {
        listen 80;

        root /usr/share/nginx/html;  # Path to your built files
        index index.html;  # Default file to serve

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ^~ /authentication/ {
            proxy_pass http://backend:3000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;
        }

        location /api/ {
            proxy_pass http://backend:3000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;
        }
    }
}