spring.application.name=catalyst

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

server.tomcat.relaxed-query-chars=[,]

token.signing.key=${JWT_SECRET_KEY}

catalyst.admin.username=${ADMIN_USER}
catalyst.admin.password=${ADMIN_PASSWORD}
catalyst.capes.directory=${CAPES_DIRECTORY}
catalyst.rate-limiting.capacity=${RATE_LIMITING_CAPACITY}
catalyst.rate-limiting.refill-minutes=${RATE_LIMITING_REFILL_MINUTES}

springdoc.swagger-ui.path=/swagger-ui.html

server.port=3000